scrape_configs:
  - job_name: "GrafanaWorkshop"
    scrape_interval: 10s
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:57283"
        labels:
          application: "Grafana Workshop"
